version: '3.1'

services:
  prometheus:
    image: prom1.2:latest
    expose:
      - 9090
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  grafan:
    image: grafana/grafana
    ports:
      - 3000:3000
